### ISSUE TITLE
Possible release 0.2.4 sooner rather than later?

### ISSUE THREAD

**Issue by eddelbuettel** [rcppsmc/rcppsmc#62]
Now that we merged, shall I cut a release?  (In the "we could maybe have had monthly releases during GSoC too" sense of not waiting for perfection but putting markers every now and then.)

Or is there consensus to wait?

To release, we'd need a NEWS.Rd file update and @ilyaZar  could maybe take a stab at summarising the four PRs since 0.2.4 in four or so bullet points.

**Comment by ilyaZar** [comment]
Hi @eddelbuettel that's a great idea!

I do not have experience on the level of (miss)perfection things may have in a new release. Some things crossing my mind on "unresolved" features (the importance of which I cannot assess properly) are:

1. @LeahPrice had some questions regarding Algorithm 6 which I want to take on next week. 
2. @adamjohansen fancied a linear Gaussian example (a small one, which could be integrated directly into the `RcppSMC` package as a package example I suppose?)

In any case, I'll definitely update NEWS.Rd. I should probably do that within #61 , or?
(I think it's a good fit, since this PR is also concerned with various minor "fixes" regarding the documentation which I believe should be done before a release: we do not need to include all changes of this PR but an updated `TODO` and and `README` file are probably reasonable)

**Comment by eddelbuettel** [comment]
Yes within #61 works or if you want to expedite it just write four ascii bullet points below and I copy it in.

**Comment by eddelbuettel** [comment]
In a nutshell, my (weakly held) position is to release now and while #61 is cooking and while some improvements are contemplated.

In practice, I have seen such improvements take months if not years.  If we wait for them then we deprive (CRAN rather than GitHub) users of the improvement.   There is value in "release early, release often [enough[".

That said, I understand that sometimes things are not quite ready.  It's not a black-or-white question with clear cut answers.

**Comment by adamjohansen** [comment]
A release soon would be good.

If we could do a little bit more testing with a linear Gaussian example to check that it doesn't throw up any surpriss then I'd be a bit more comfortable because it's difficult to be entirely sure there aren't any significant gremlins lurking without a bit of "real" testing, but I don't feel that strongly and I certainly wouldn't want to delay things significantly.

**Comment by LeahPrice** [comment]
A release soon sounds like a good idea to me too. I don't feel particularly strongly about it but I'd also be more comfortable if we had an example somewhere that tested the latest algorithms. I think that's more important than my questions about algorithm 6, which are possibly just from me not being very familiar with the algorithm.

**Comment by eddelbuettel** [comment]
(We could still release, getting three months of work out, and then i) clean up docs, ii) add an example, iii) figure out if/how we want to do with whitespace if anything and follow-up with another two or three weeks later.

**Comment by ilyaZar** [comment]
I have a tendency to agree with @eddelbuettel  since it's probably really more of a "deprive CRAN users than GitHub users from improvements".

Also we would have more frequent releases indicating that the project moves forward and i) to iii) could already be the next release (in a 2/3 weeks or so) showing that work progresses irrespective of GSoC being over.

**Comment by eddelbuettel** [comment]
When is your GSoC 'drop-dead' deadline?  If we have the package up in a day or two (likely, no smoking gun I know of) you can claim the scalp of :shipit: [1].  No errors in local testing, I just shipped the tarball to RHub to test on the other platforms I do not have.


[1] That is an apparent inside joke from work nobody knows the source of but many use; apparently some cultures use squirrels to denote "hell yeah it shipped"; I now follow along :grin:)

**Comment by ilyaZar** [comment]
Today, 19:59 German time is the final-final deadline, I just submitted the final part anyway. 

It would have been certainly great to have that shipped squirrel :) But I guess it's too timely to include it into this GSoC today, and, anyway, a long term engagement in this project is what matters to me: aiming at collecting more shipped squirrels with future releases!

**Comment by eddelbuettel** [comment]
BTW I ran the tests locally and at rhub and we're clean.  So shall we merge the pending PR and call it 0.2.4 then?

**Comment by adamjohansen** [comment]
Fine with me.

**Comment by eddelbuettel** [comment]
I can take care of it this evening (aka Leah's Tuesday morning).  We will be missing the GSoC deadline by mere hours but we did good anyway. 

The package is otherwise in good standing at CRAN so we should be updated in no time.

**Comment by eddelbuettel** [comment]
I missed this little detail:

![image](https://user-images.githubusercontent.com/673121/130614251-9a5125ae-391a-458f-a7dd-838a9bfd8ad7.png)

Usually they pre-announce this by email; if they did this time I missed it too...   So once it reopens in a week.

**Comment by ilyaZar** [comment]
Well, after the whole hassle in the past 1.5 years, vacation is very much in demand probably everywhere :) 

The following is off topic regarding 0.2.4 , but maybe the information is useful (I found that by coincidence some days ago..., and have not been informed via any Email/channel either...):

The RStudio team will be soon on leave too, see  https://www.rstudio.com/r-and-r/. 

Just mentioning this, in case anybody here is in touch or requires support/services from their side.

**Comment by eddelbuettel** [comment]
CRAN has regular breaks, often over Christmas, which they use to update the systems. If memory serves it was also closed a few times around R major version changes. I just don't recall one middle of summer.  Oh well.

**Comment by eddelbuettel** [comment]
This of course gives us a few days to polish 0.2.4.  One thing I came across is that your paragraphs were a little wider than what the default has so I whitespace-changed ChangeLog and inst/NEWS.Rd.  No actual changes.

**Comment by ilyaZar** [comment]
Thanks, I think I'll try to use .editorconfig now, it works with vscode too! Should not happen again!

**Comment by eddelbuettel** [comment]
CRAN is open, and apparently buys :).  Submitted the package earlier, it is still in pre-Test.  I am sure we will hear from them.

```sh
edd@rob:~$ cranIncoming.r RcppSMC             # another littler script of mine
 package version cran_folder                time size
 RcppSMC   0.2.4     pretest 2021-09-01 13:48:00  58K
edd@rob:~$ 
```

**Comment by eddelbuettel** [comment]
Slow progress. It has now left `pretest`, has been built and will be looked at.  Should be fast (in normal times), they are still swamped it seems but maybe today with some luck.

**Comment by eddelbuettel** [comment]
And with that we're on CRAN.  Congratulation to CRAN package co-author @ilyaZar  :clap:   :100: 

![image](https://user-images.githubusercontent.com/673121/131922189-d4ad5cb6-072f-47ca-a908-b1023b2da846.png)

(and I had gotten the email just minutes earlier...)
